KERNEL_SRC := ../linux-5.4

.PHONY: all

all:
		$(MAKE) -C $(KERNEL_SRC) O=$(abspath .) prepare

.config:
		@echo "No config file present, taking $(KERNEL_SRC)/boost.config"
		cp $(KERNEL_SRC)/boost.config .config
